/*Write a multithreaded program that generates the Fibonacci series. The program
should work as follows: The user will enter on the command line the number of
Fibonacci numbers that the program is to generate. The program then will create a
separate thread that will generate the Fibonacci numbers, placing the sequence in
data that is shared by the threads (an array is probably the most convenient data
structure). When the thread finishes execution the parent will output the sequence
generated by the child thread. Because the parent thread cannot begin outputting the
Fibonacci sequence until the child thread finishes, this will require having the parent
thread wait for the child thread to finish.*/

#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>

void *thread_code(void *args)
{
	int *arr=(int *)args; 
	int n=arr[0]; 
	arr[1]=0; 
	arr[2]=1; 
	for(int i=3; i<=n; i++)
	{
		arr[i]=arr[i-1]+arr[i-2]; 
	}
}
int main(int argc, char *argv[])
{
	if(argc<2)
	{
		printf("Not enough arguments!\n"); 
		exit(EXIT_FAILURE); 
	}
	int n=atoi(argv[1]); 
	int *arr=(int *)calloc(n+1, sizeof(int)); 
	arr[0]=n; 
	
	pthread_t thread;
	pthread_create(&thread, 0, &thread_code, (void*)arr); 
	pthread_join(thread, 0); 
	printf("The Fibonacci Series is: "); 
	for(int i=1; i<=n; i++)
	{
		printf("%d ", arr[i]); 
	}
	printf("\n"); 
	return 0; 
}